fix: do not use a remote svg image in preview
serverless-stack/serverless-stack pull request #1233
Opened 2022-01-05 04:52 UTC by Manitej66

2022-01-05 14:13 UTC, thdxr requested changes
Do you think we can use one of the react icons here?

2022-01-05 14:16 UTC, Manitej66 commented
> Do you think we can use one of the react icons here?

Yeah we can, but we're changing the src value dynamically so I kept the local image.

We can conditionally render icon vs image, but changing the image src dynamically makes more sense i believe

2022-01-05 18:02 UTC, thdxr commented
I think we should swap out the element because for SVGs rendering them in an `img` element isn't entirely right.  react-icons runs all the svgs through SVGR which places the svg directly on the page

2022-01-06 14:18 UTC, thdxr requested changes

2022-01-06 14:18 UTC, thdxr commented on packages/console/src/App/Stage/Buckets/Detail.tsx
> +              style={{ margin: "0 auto" }}
Avoid inline styles, wrap this in a styled component

2022-01-06 17:20 UTC, thdxr requested changes

2022-01-06 17:20 UTC, thdxr commented on packages/console/src/App/Stage/Buckets/Detail.tsx
> +            <Placeholder>
Sorry I actually meant you can wrap the icon directly like this

```
const Placeholder = styled(ImFileEmpty, { ... })
```

2022-01-07 17:05 UTC, merged